"""add currency to users

Revision ID: 20251006_0001
Revises: 20251005_0001
Create Date: 2025-10-06 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20251006_0001'
down_revision: Union[str, None] = '20251005_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('currency', sa.String(length=8), nullable=False, server_default='USD'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'currency')
    # ### end Alembic commands ###
